apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world-errbot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Errbot World app
  sourceRepos:
    - '*'  # Allow all repos, restrict as needed
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'