apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-bb
  labels:
    app: hello-world-bb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-bb
  template:
    metadata:
      labels:
        app: hello-world-bb
    spec:
      containers:
      - name: hello-world-bb
        image: busybox:1.35.0 
        command: ["sh", "-c", "while true; do echo 'Hello World from App2'; sleep 3600; done"]
        # The image is changed to busybox for a simple echo command
        # The command is set to run an infinite loop that echoes a message
        # This is a simple way to demonstrate the deployment without needing a web server
        ports:
        - containerPort: 80