apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:latest
        ports:
        - containerPort: 80

---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: hello-world-config
#  namespace: hw
#data:
#  APP_NAME: "HelloWorldApp"
#  APP_ENV: "production"
#  APP_VERSION: "1.0.0"
#  BLUE: "Blah"